baseURL: "https://wadeallen.me"
title: Wade Allen
paginate: 5
theme: PaperMod

build:
  buildFuture: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

menu:
    main:
        - identifier: archive
          name: worship planning
          url: /archive/
          weight: 10
