baseURL: "https://wadeallen.netlify.app"
title: Wade Allen
paginate: 5
theme: PaperMod

build:
  buildFuture: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

menu:
    main:
        - identifier: archive
          name: worship planning
          url: /archive/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identifier: wadeallen
          name: wadeallen.me
          url: https://wadeallen.me
          weight: 30
